language: node_js
node_js:
  - "10"

branches:
  only:
  - dev



script:
  - npm ci
  - npm run build

cache:
  directories:
    - "node_modules"

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep-history: true
  target-branch: master
  on:
    branch: dev